insert into CURRANCY_EXCHANGE
(ID,CURRANCY_FROM,CURRANCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10001,'USD','INR',65,'');
insert into CURRANCY_EXCHANGE
(ID,CURRANCY_FROM,CURRANCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10002,'EUR','INR',75,'');
insert into CURRANCY_EXCHANGE
(ID,CURRANCY_FROM,CURRANCY_TO,CONVERSION_MULTIPLE,ENVIRONMENT)
values(10003,'AUD','INR',25,'');